language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lowriderow/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lowriderow/docker-react npm run test